# Generated by Django 5.2.4 on 2025-07-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('picture', models.URLField(default='https://static01.nyt.com/images/2025/06/23/multimedia/23best-restaurants-philly-update1-gvkc/23best-restaurants-philly-update1-gvkc-articleLarge.jpg?quality=75&auto=webp&disable=upscale')),
                ('cuisine', models.CharField(max_length=100)),
                ('rating', models.FloatField()),
            ],
        ),
    ]
