# Generated by Django 5.2.4 on 2025-07-25 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_remove_cart_items_cartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(related_name='carts', to='delivery.menuitem'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
